targets:
  $default:
    sources:
      - 'l10n/src/**.arb'
      - '$package$'
      - 'lib/$lib$'
    builders:
      merge_arb:
        options:
          input_folder: 'l10n/src'
          output_folder: 'lib/l10n/generated_code'
          supported_locales: ['th', 'en']
