targets:
  $default:
    builders:
      merge_arb:
        options:
          input_path: 'lib/l10n/src/*.arb'
          output_folder: 'lib/l10n/generated_code'
          supported_locales: ['th', 'en']
