# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config

builders:
  merge_arb:
    import: "package:merge_arb/merge_arb.dart"
    builder_factories: ["mergeArbBuilderFactory"]
    build_extensions: {'lib/$lib$': ['.merged.arb']}
    auto_apply: root_package
    build_to: source
    defaults:
      options:
        input_path: 'l10n/src/*.arb'
        output_folder: 'lib/l10n/generated_code'