name: merge_arb
description: Codegen that merges multiple ARB files into a single ARB file.
version: 1.0.0
repository: https://github.com/ltman/merge_arb

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

issue_tracker: https://github.com/ltman/merge_arb/issues

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  glob: ^2.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
